[package]
name = "cuddly-jumpers"
version = "0.1.0"
authors = ["Jakub Konka <jakub.konka@golem.network>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
remote-fn = { path = "crates/remote-fn" }
gwasm-api = "0.1.1"

[workspace]
