[package]
name = "gfaas"
version = "0.1.0"
authors = ["Jakub Konka <jakub.konka@golem.network>"]
edition = "2018"

[dependencies]
gfaas-macro = { path = "crates/macro" }
gwasm-api = "0.2"
tempfile = "3.1"
tokio = { version = "0.2", features = ["blocking"] }
# sp-wasm-engine = "0.3"
sp-wasm-engine = { path = "../sp-wasm/sp-wasm-engine" }
lazy_static = "1.4"

[workspace]
members = [
    "crates/cli",
]
exclude = [
    "examples/hello",
    "examples/sum",
]
