[package]
name = "gfaas"
version = "0.1.0"
authors = ["Jakub Konka <jakub.konka@golem.network>"]
edition = "2018"

[dependencies]
gfaas-macro = { path = "crates/macro" }
gwasm-api = "0.1"
tempfile = "3.1"

[workspace]
members = ["crates/cli"]
