[package]
name = "sum"
version = "0.1.0"
authors = ["Jakub Konka <jakub.konka@golem.network>"]
edition = "2018"

[dependencies]
gfaas = { path = "../../" }
actix-rt = "1"
futures = "0.3"
serde_json = "1"

[gfaas_dependencies]
serde_json = "1"
